### ISSUE TITLE
How about hexaploid?

### ISSUE THREAD

**Issue by sanvva** [clwgg/nQuire#1]
Great software! I doubt that my sample is hexaploidy. After running nQuire, tetraploid is given.

**Comment by clwgg** [comment]
Hi sanvva,

unfortunately, nQuire currently is only usable to distinguish di-, tri- and tetraploids. The model isn't really easily extendable to higher ploidies, as probability densities start overlapping heavily in the frequency spectrum of biallelic sites.

Sorry!

**Comment by bagdevi** [comment]
I am also looking forward to the possibility of hexaploid genomes.
