### ISSUE TITLE
nQuire with low coverage and complex genomes

### ISSUE THREAD

**Issue by dcopetti** [clwgg/nQuire#3]
Hello,

I wonder if it will make sense to use nQuire to assess the ploidy level of a series of plant genome assemblies I have. The assemblies span 600-1000 Mb (estimated size 1000-1600 Mb), are from heterozygous outcrossing wild species and all the data I have is about 20-25x Illumina PE data (the assemblies are made in a reference-based manner).
Is my dataset suitable to be used by this software?
Thanks,

Dario

**Comment by clwgg** [comment]
Hi Dario,

20-25x is definitely on the low end, as you can see in the coverage benchmarks in Figures 2 and 3 of the [paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2128-z#Sec6). You can play around with the data a bit with the utilities implemented in nQuire, but you'll have to take the results with a grain of salt. I'd build a bin file (`nQuire create`) and see how the histogram looks (`nQuire histo`). You can also try to filter the positions going into the analysis, e.g. based on genome annotation if you have reasonable expectations of more or less complex/repetitive regions. This is discussed in the second half of the discussion of the paper linked above.
If you'd like to check for ploidy variation in your dataset, you can run the model an all samples (`nQuire lrdmodel *.bin`) and see if the relative magnitudes of the delta-loglikelihoods behave differently or similarly between samples (last three columns of the output file, also described in the README of the repo).

**Comment by CosterwellKhyriem** [comment]
Hi,
When I try to install nQuire it gave me the following error. I have installed all the require libraries. 
Please help.
Thanks

echo '/* This config.h disables LIBBZ2 and LIBLZMA */' > htslib/config.h
echo '/* #define HAVE_LIBBZ2 1 */' >> htslib/config.h
echo '/* #define HAVE_LIBLZMA 1 */' >> htslib/config.h
echo '/* Full featured CRAM reading is not supported! */' >> htslib/config.h
echo '#define HAVE_FSEEKO 1' >> htslib/config.h
echo '#define HAVE_DRAND48 1' >> htslib/config.h
cd htslib && make libhts.a ; cd ..
make[1]: Entering directory '/home/costerwell/Apps/nQuire-master/htslib'
make[1]: *** No rule to make target 'libhts.a'.  Stop.
make[1]: Leaving directory '/home/costerwell/Apps/nQuire-master/htslib'

**Comment by clwgg** [comment]
> Hi,
> When I try to install nQuire it gave me the following error. I have installed all the require libraries.
> Please help.
> Thanks
> 
> echo '/* This config.h disables LIBBZ2 and LIBLZMA _/' > htslib/config.h echo '/_ #define HAVE_LIBBZ2 1 _/' >> htslib/config.h echo '/_ #define HAVE_LIBLZMA 1 _/' >> htslib/config.h echo '/_ Full featured CRAM reading is not supported! */' >> htslib/config.h
> echo '#define HAVE_FSEEKO 1' >> htslib/config.h
> echo '#define HAVE_DRAND48 1' >> htslib/config.h
> cd htslib && make libhts.a ; cd ..
> make[1]: Entering directory '/home/costerwell/Apps/nQuire-master/htslib'
> make[1]: *** No rule to make target 'libhts.a'. Stop.
> make[1]: Leaving directory '/home/costerwell/Apps/nQuire-master/htslib'

Did you clone the repository recursively? It seems the htslib repo might be missing.
