### ISSUE TITLE
Applying pipeline to error-prone long reads

### ISSUE THREAD

**Issue by chocotwig** [clwgg/nQuire#7]
Hi, 

Do you have suggestions for applying nQuire to nanopore/error-prone sequencing reads?

Thanks!

**Comment by clwgg** [comment]
Hi,
not really unfortunately -- I have never played with it myself. I would suspect that you would want to increase the minimum coverage, as well as the minimum mapping quality, as you will require quite a substantial amount of bases covering any given site to increase signal vs. noise.
